using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
/*******************************************************************************
*Create By CG
*Function 
*******************************************************************************/
namespace ZXK.ZWQG
{
	public class OptionItemCtrl : MonoBehaviour
	{
        public string _RightAnswer;

        private ThemeCtrl _mainThemeCtrl = null;
        public void Init(ThemeCtrl ctrl)
        {
            _mainThemeCtrl = ctrl;
            transform.GetComponent<Button>().onClick.AddListener(() =>
            {
                if (transform.name.Equals(_RightAnswer))
                {
                    _mainThemeCtrl.SelectRightOption();
                }
            });
        }
    }
}